import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import commands from "../config/commands.json";
import pkg from "../package.json";
import mod from "../config/mod.json";
import gameplay from "../config/gameplay.json";
import { SETTINGS } from "../config/settings";
import { PROJECT_ROOT } from "../src/config";

function lua(value: unknown): string {
  if (value === null || value === undefined) return "nil";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value !== "object") return String(value);
  if (Array.isArray(value)) return `{${value.map(lua).join(",")}}`;
  return `{${Object.entries(value)
    .map(([key, item]) => `[${lua(key)}]=${lua(item)}`)
    .join(",")}}`;
}

export function generate(check = false): void {
  const files = {
    "factorio-mod/commands/contract.lua": `-- Generated by bun run generate from config/commands.json. Do not edit.\nreturn ${lua(commands)}\n`,
    "factorio-mod/info.json": JSON.stringify({ ...mod, version: pkg.version }, null, 2) + "\n",
    "factorio-mod/commands/settings.lua": `-- Generated by bun run generate from config/gameplay.json. Do not edit.\nreturn ${lua(gameplay)}\n`,
    ".env.example":
      "# Generated from config/settings.ts; copy to .env and edit your values.\n\n" +
      Object.entries(SETTINGS)
        .map(([name, config]) => `# ${config.description}\n${name}=${config.default}\n`)
        .join("\n"),
  };
  for (const [path, content] of Object.entries(files)) {
    const absolute = resolve(PROJECT_ROOT, path);
    if (check) {
      if (readFileSync(absolute, "utf8") !== content)
        throw new Error(`${path} is stale; run bun run generate`);
    } else writeFileSync(absolute, content);
  }
}
if (import.meta.main) generate(process.argv.includes("--check"));
